DEFAULT_CACHE_TTL_SECONDS = 300
DEFAULT_AUTH_CACHE_TTL_SECONDS = 7 * 24 * 60 * 60
DEFAULT_WAKE_REFRESH_IDLE_SECONDS = 5 * 60
DEFAULT_RECURRING_THROTTLE_SECONDS = 5 * 60

BROWSER_CACHE_TTL_SECONDS = 10 * 24 * 60 * 60
BALANCE_HISTORY_TABLE_LIMIT = 6
RECENT_TRANSACTIONS_CACHE_LIMIT = 6
RECURRING_RULE_TABLE_LIMIT = 6
SPLIT_ENTRY_TABLE_LIMIT = 6
SPLIT_DOCUMENT_TABLE_LIMIT = 6
TRIP_TABLE_LIMIT = 6
TRANSACTION_PAGE_SIZE = 6
BROWSER_CACHE_BALANCE_HISTORY = BALANCE_HISTORY_TABLE_LIMIT
BROWSER_CACHE_RECENT_TRANSACTIONS = RECENT_TRANSACTIONS_CACHE_LIMIT

SYNC_STATUS_POLL_SECONDS = 12
