DEFAULT_CACHE_TTL_SECONDS = 300
DEFAULT_AUTH_CACHE_TTL_SECONDS = 7 * 24 * 60 * 60
DEFAULT_WAKE_REFRESH_IDLE_SECONDS = 5 * 60
DEFAULT_RECURRING_THROTTLE_SECONDS = 5 * 60

BROWSER_CACHE_TTL_SECONDS = 10 * 24 * 60 * 60
BROWSER_CACHE_RECENT_TRANSACTIONS = 10
BROWSER_CACHE_BALANCE_HISTORY = 10

SYNC_STATUS_POLL_SECONDS = 12
