DEFAULT_RECURRING_THROTTLE_SECONDS = 5 * 60

BALANCE_HISTORY_TABLE_LIMIT = 12
RECURRING_RULE_TABLE_LIMIT = 12
SPLIT_ENTRY_TABLE_LIMIT = 12
SPLIT_DOCUMENT_TABLE_LIMIT = 12
TRIP_TABLE_LIMIT = 12
TRANSACTION_PAGE_SIZE = 12
